### ISSUE TITLE
Receiving wrong values in arrEcgContent array

### ISSUE THREAD

**Issue by Nafees1** [viatom-dev/VTProLib#1]
I am using the SDK with pulsebit ex device. Device is connecting correctly with bluetooth. After I retrieve a detail Ecg object as "VTProEcgDetail" , the problem is that the values in arrEcgContent array is wrong while the other values like heart rate , ecgResult  , date , timeLength etc  are correct.
Can you please tell me what's going wrong here?
 Also the values in arrEcgContent array are in range between -5 to 5.

**Comment by viatom-dev** [comment]
The parser not support Pulsebit EX device. 
I will add support for EX in the new version.
